language: java
notifications:
  slack: hivexteam:xoSLoB9jIPnYqMcHLIesSlDZ
  email: false
before_install:
  - nvm install node
  - nvm use node
  - npm install --global mocha
  - cd src/main/webapp/js/
  - npm test
  - cd ../../../..
before_deploy:
  - cd target
  - jar -xvf swedesigner.war
  - cd ..
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIJQDT6MLH3RIIEAQ
  secret_access_key:
    secure: "E4XnRRC/ayQcLJOKGO+K82tqvQyBQc/YQHkj9h76rWi8LuP7IrtPPnplOSutPdP9Rg86UgRFIH9Nya9JRHupp6C2u1MMSj3c4SIsb9ZYA7uj+YzcFtW7OqO+PqDlTgLMNLM7pfqYAso9lwlx9moBwEaGRsYdQcTDoOo9NZQBmbjm0Jooqc33P0v3Na0AgcQFRD6MdO+ZbsNnjsy3CzYAZHOrTF0fSsmy60xBcg0ydfMN/DNW1fTll4UxbVTe8TJxsxmNnIKo1JbPyqmnfQ8oyR4/AmNK82G55aiOY3V6ZKAlxgiPPcn+PWQhwtP07ZBlmorgMSPZ1XmERk1dRnmbAOGNWtW8X7YbqTuVzvmoW3n0wvjnZ1dEKVyFAYahgM3FSUcr5hhjry7e7IcOX/hSiFSWkks0bYc/BkAVKoFIa3300/8xsqaRLfMeJwOXDFqQsnhfrZrZrJZR1mWC4vJBmVL3CiHtPLYX5g5cF7DU9WVd8q/SEd1/OSaAT0YoqsR7hBXQLHvivp3Q6koGnjZgnEY2zOgviQfRc93frbIdbduxl31MK8s1pxHBoNTaKio5GU2KNTPhAHMRz2WPMm9NYVrYDzNRRWmnvvu6jcreRmrdf+cCBAG5UmC3DGBIhI4GQLPSax2XpWG0i9fz7qhJvdePBgfOVBmjZc5B2dh0YoA="
  skip_cleanup: true
  app: SWEDesigner
  env: LowCost-env
  region: eu-central-1
  bucket_name: elasticbeanstalk-eu-central-1-538360443246
