language: java
notifications:
  slack: hivexteam:xoSLoB9jIPnYqMcHLIesSlDZ
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: AKIAIJQDT6MLH3RIIEAQ
  secret_access_key:
    secure: J1Gx30gL85iBMgHWmTuQX+aggBG00VJH4ehi9qqilVUMv766OPtjafrVfMYOZszZkouoz7nLIwGyR8er0ehvV9J/aoRzAFhWqWe7cbw7/4AwX6AKOQu8edhVPbIH2MAg8wsQMb9ina+5cKbxwkNux9eYGEPuHHVEjVPy4xOs9lFuGU6BK0/UHl3EjtohFWn58tOzg75eejnTaJ9K+oT1gvvYRLuc9axp98K/vkk8Iq5maNdLtTHvZfNRAVAS6Ld+HnckS9gzzoN6uz4WnvPj2VBVT9ocohPx6PaATw4YRlvm9C+eeEUolspDI+ZRbxKAaFKk0aV5R4fdcvs0AxbuHybDOKbCVUTA8XMDQXUCOnXsIaKYwFYtSVG3KzD5RTewENju8ILlYUQ93WEii6O0vzKyXVsSqDGdetGa6bYXoTE5EJeCpaR/urnj88RnktGZB5pmRiPLyN0J9tYo1Eyg5W5Xk8AoldDyzJUEFuvzcwV7X9FDNlllTD+EXvDewiuEjCeL5ftOwOPQxI0eN33AFlqRlN0DmKcgevky5SkmiahaEqQCIzysteKq5ya8J+r6YXW5JfOAYwzlfdv3MGxIIrXeYSSfnOLxa4q9COqJHFdlgyMdnCH9tGlucslGBVcrJTTN9kGjeUOM6WxsccvE8ajzpBxGjeh9X5D78GyZsog=
  app: SWEDesigner
  env: LowCost-env
  region: eu-central-1
