language: java
notifications:
  slack: hivexteam:xoSLoB9jIPnYqMcHLIesSlDZ
# before_install:
#   - nvm install node
#   - nvm use node
#   - npm install --save-dev mocha
#   - npm test
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  app: SWEDesigner
  env: LowCost-env
  region: eu-central-1
  access_key_id: AKIAIJQDT6MLH3RIIEAQ
  secret_access_key:
    secure: "gF8TPMXNak2kDoBY3dfJm+jsoMCK/rxD//FGSNgF7n11O4X7ra/rE/cON6v9r+1pk41Anc7JKefxiKaEJlgS+DsAV8H60F9OhP5ar48mm8Lt9c+hZ9SzxSH8m4vM7wNKb+5t8NWw/Ex9fejkos8Oivu7YUq7VXuX9eglxyKFI9lWUlTa892W5xXHpCyvBomjzJOikuY3u8yNNmBLlFyM5Ra38LVqotn4pkv9CcdO7PcEtrY9+arZCxnpxFBiIV1Yo53Fo1voO5w+8dWadsxul2DUCq3ZoNgqgIAGFnZtOatwvlcEvjQYgvYbWK2dnnRO7G3QMBvNYGV04Ut3Z9+mzD+h/yMh51i6LTFMdJt6t4f7ILlTF+CsGk64Ht/ehKbgU22NuXegwl3RxYq1Y6xwO5qBAdNdybXmyPI4wAlktjjaTsIaspJXHAvdDmByGsyZT9CBl0pctj3HkP2vUQ7Wk6egf5+wp2CVFhd2iXrwuQN/M2FGbdyjjWhqYoEz6xu/LnaCaM40q3YfO9L4oN9/VQYgsKBXYaEVzVnWmhUYD11BuMqZat9bVMzLsg2LqLmsQNN6x6KUrt9dh99geIenwwcWMPxyBgm+xaa3u51q3tasbTahmF3PNR6cdmyzpIo98oNd96DuUifqrVJP6l1v4J3rwMVF2OVTs8JcPVT6mPg="
